// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phrasebook.Data.Sql;

namespace PhrasebookBackendService.Migrations
{
    [DbContext(typeof(PhrasebookDbContext))]
    [Migration("20211128003254_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Phrasebook.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstLanguageId")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ForeignLanguageId")
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirstLanguageId");

                    b.HasIndex("ForeignLanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("Phrasebooks");
                });

            modelBuilder.Entity("Phrasebook.Data.Models.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = "ab",
                            DisplayName = "Abkhaz"
                        },
                        new
                        {
                            Id = "aa",
                            DisplayName = "Afar"
                        },
                        new
                        {
                            Id = "af",
                            DisplayName = "Afrikaans"
                        },
                        new
                        {
                            Id = "ak",
                            DisplayName = "Akan"
                        },
                        new
                        {
                            Id = "sq",
                            DisplayName = "Albanian"
                        },
                        new
                        {
                            Id = "am",
                            DisplayName = "Amharic"
                        },
                        new
                        {
                            Id = "ar",
                            DisplayName = "Arabic"
                        },
                        new
                        {
                            Id = "an",
                            DisplayName = "Aragonese"
                        },
                        new
                        {
                            Id = "hy",
                            DisplayName = "Armenian"
                        },
                        new
                        {
                            Id = "as",
                            DisplayName = "Assamese"
                        },
                        new
                        {
                            Id = "av",
                            DisplayName = "Avaric"
                        },
                        new
                        {
                            Id = "ae",
                            DisplayName = "Avestan"
                        },
                        new
                        {
                            Id = "ay",
                            DisplayName = "Aymara"
                        },
                        new
                        {
                            Id = "az",
                            DisplayName = "Azerbaijani"
                        },
                        new
                        {
                            Id = "bm",
                            DisplayName = "Bambara"
                        },
                        new
                        {
                            Id = "ba",
                            DisplayName = "Bashkir"
                        },
                        new
                        {
                            Id = "eu",
                            DisplayName = "Basque"
                        },
                        new
                        {
                            Id = "be",
                            DisplayName = "Belarusian"
                        },
                        new
                        {
                            Id = "bn",
                            DisplayName = "Bengali"
                        },
                        new
                        {
                            Id = "bh",
                            DisplayName = "Bihari"
                        },
                        new
                        {
                            Id = "bi",
                            DisplayName = "Bislama"
                        },
                        new
                        {
                            Id = "bs",
                            DisplayName = "Bosnian"
                        },
                        new
                        {
                            Id = "br",
                            DisplayName = "Breton"
                        },
                        new
                        {
                            Id = "bg",
                            DisplayName = "Bulgarian"
                        },
                        new
                        {
                            Id = "my",
                            DisplayName = "Burmese"
                        },
                        new
                        {
                            Id = "ca",
                            DisplayName = "Catalan"
                        },
                        new
                        {
                            Id = "ch",
                            DisplayName = "Chamorro"
                        },
                        new
                        {
                            Id = "ce",
                            DisplayName = "Chechen"
                        },
                        new
                        {
                            Id = "ny",
                            DisplayName = "Chichewa"
                        },
                        new
                        {
                            Id = "zh",
                            DisplayName = "Chinese"
                        },
                        new
                        {
                            Id = "cv",
                            DisplayName = "Chuvash"
                        },
                        new
                        {
                            Id = "kw",
                            DisplayName = "Cornish"
                        },
                        new
                        {
                            Id = "co",
                            DisplayName = "Corsican"
                        },
                        new
                        {
                            Id = "cr",
                            DisplayName = "Cree"
                        },
                        new
                        {
                            Id = "hr",
                            DisplayName = "Croatian"
                        },
                        new
                        {
                            Id = "cs",
                            DisplayName = "Czech"
                        },
                        new
                        {
                            Id = "da",
                            DisplayName = "Danish"
                        },
                        new
                        {
                            Id = "dv",
                            DisplayName = "Divehi"
                        },
                        new
                        {
                            Id = "nl",
                            DisplayName = "Dutch"
                        },
                        new
                        {
                            Id = "en",
                            DisplayName = "English"
                        },
                        new
                        {
                            Id = "eo",
                            DisplayName = "Esperanto"
                        },
                        new
                        {
                            Id = "et",
                            DisplayName = "Estonian"
                        },
                        new
                        {
                            Id = "ee",
                            DisplayName = "Ewe"
                        },
                        new
                        {
                            Id = "fo",
                            DisplayName = "Faroese"
                        },
                        new
                        {
                            Id = "fj",
                            DisplayName = "Fijian"
                        },
                        new
                        {
                            Id = "fi",
                            DisplayName = "Finnish"
                        },
                        new
                        {
                            Id = "fr",
                            DisplayName = "French"
                        },
                        new
                        {
                            Id = "ff",
                            DisplayName = "Fula"
                        },
                        new
                        {
                            Id = "gl",
                            DisplayName = "Galician"
                        },
                        new
                        {
                            Id = "ka",
                            DisplayName = "Georgian"
                        },
                        new
                        {
                            Id = "de",
                            DisplayName = "German"
                        },
                        new
                        {
                            Id = "el",
                            DisplayName = "Greek"
                        },
                        new
                        {
                            Id = "gn",
                            DisplayName = "Guaraní"
                        },
                        new
                        {
                            Id = "gu",
                            DisplayName = "Gujarati"
                        },
                        new
                        {
                            Id = "ht",
                            DisplayName = "Haitian"
                        },
                        new
                        {
                            Id = "ha",
                            DisplayName = "Hausa"
                        },
                        new
                        {
                            Id = "he",
                            DisplayName = "Hebrew (modern)"
                        },
                        new
                        {
                            Id = "hz",
                            DisplayName = "Herero"
                        },
                        new
                        {
                            Id = "hi",
                            DisplayName = "Hindi"
                        },
                        new
                        {
                            Id = "ho",
                            DisplayName = "Hiri Motu"
                        },
                        new
                        {
                            Id = "hu",
                            DisplayName = "Hungarian"
                        },
                        new
                        {
                            Id = "ia",
                            DisplayName = "Interlingua"
                        },
                        new
                        {
                            Id = "id",
                            DisplayName = "Indonesian"
                        },
                        new
                        {
                            Id = "ie",
                            DisplayName = "Interlingue"
                        },
                        new
                        {
                            Id = "ga",
                            DisplayName = "Irish"
                        },
                        new
                        {
                            Id = "ig",
                            DisplayName = "Igbo"
                        },
                        new
                        {
                            Id = "ik",
                            DisplayName = "Inupiaq"
                        },
                        new
                        {
                            Id = "io",
                            DisplayName = "Ido"
                        },
                        new
                        {
                            Id = "is",
                            DisplayName = "Icelandic"
                        },
                        new
                        {
                            Id = "it",
                            DisplayName = "Italian"
                        },
                        new
                        {
                            Id = "iu",
                            DisplayName = "Inuktitut"
                        },
                        new
                        {
                            Id = "ja",
                            DisplayName = "Japanese"
                        },
                        new
                        {
                            Id = "jv",
                            DisplayName = "Javanese"
                        },
                        new
                        {
                            Id = "kl",
                            DisplayName = "Kalaallisut"
                        },
                        new
                        {
                            Id = "kn",
                            DisplayName = "Kannada"
                        },
                        new
                        {
                            Id = "kr",
                            DisplayName = "Kanuri"
                        },
                        new
                        {
                            Id = "ks",
                            DisplayName = "Kashmiri"
                        },
                        new
                        {
                            Id = "kk",
                            DisplayName = "Kazakh"
                        },
                        new
                        {
                            Id = "km",
                            DisplayName = "Khmer"
                        },
                        new
                        {
                            Id = "ki",
                            DisplayName = "Kikuyu"
                        },
                        new
                        {
                            Id = "rw",
                            DisplayName = "Kinyarwanda"
                        },
                        new
                        {
                            Id = "ky",
                            DisplayName = "Kirghiz"
                        },
                        new
                        {
                            Id = "kv",
                            DisplayName = "Komi"
                        },
                        new
                        {
                            Id = "kg",
                            DisplayName = "Kongo"
                        },
                        new
                        {
                            Id = "ko",
                            DisplayName = "Korean"
                        },
                        new
                        {
                            Id = "ku",
                            DisplayName = "Kurdish"
                        },
                        new
                        {
                            Id = "kj",
                            DisplayName = "Kwanyama"
                        },
                        new
                        {
                            Id = "la",
                            DisplayName = "Latin"
                        },
                        new
                        {
                            Id = "lb",
                            DisplayName = "Luxembourgish"
                        },
                        new
                        {
                            Id = "lg",
                            DisplayName = "Luganda"
                        },
                        new
                        {
                            Id = "li",
                            DisplayName = "Limburgish"
                        },
                        new
                        {
                            Id = "ln",
                            DisplayName = "Lingala"
                        },
                        new
                        {
                            Id = "lo",
                            DisplayName = "Lao"
                        },
                        new
                        {
                            Id = "lt",
                            DisplayName = "Lithuanian"
                        },
                        new
                        {
                            Id = "lu",
                            DisplayName = "Luba-Katanga"
                        },
                        new
                        {
                            Id = "lv",
                            DisplayName = "Latvian"
                        },
                        new
                        {
                            Id = "gv",
                            DisplayName = "Manx"
                        },
                        new
                        {
                            Id = "mk",
                            DisplayName = "Macedonian"
                        },
                        new
                        {
                            Id = "mg",
                            DisplayName = "Malagasy"
                        },
                        new
                        {
                            Id = "ms",
                            DisplayName = "Malay"
                        },
                        new
                        {
                            Id = "ml",
                            DisplayName = "Malayalam"
                        },
                        new
                        {
                            Id = "mt",
                            DisplayName = "Maltese"
                        },
                        new
                        {
                            Id = "mi",
                            DisplayName = "Māori"
                        },
                        new
                        {
                            Id = "mr",
                            DisplayName = "Marathi (Marāṭhī)"
                        },
                        new
                        {
                            Id = "mh",
                            DisplayName = "Marshallese"
                        },
                        new
                        {
                            Id = "mn",
                            DisplayName = "Mongolian"
                        },
                        new
                        {
                            Id = "na",
                            DisplayName = "Nauru"
                        },
                        new
                        {
                            Id = "nv",
                            DisplayName = "Navajo"
                        },
                        new
                        {
                            Id = "nb",
                            DisplayName = "Norwegian Bokmål"
                        },
                        new
                        {
                            Id = "nd",
                            DisplayName = "North Ndebele"
                        },
                        new
                        {
                            Id = "ne",
                            DisplayName = "Nepali"
                        },
                        new
                        {
                            Id = "ng",
                            DisplayName = "Ndonga"
                        },
                        new
                        {
                            Id = "nn",
                            DisplayName = "Norwegian Nynorsk"
                        },
                        new
                        {
                            Id = "no",
                            DisplayName = "Norwegian"
                        },
                        new
                        {
                            Id = "ii",
                            DisplayName = "Nuosu"
                        },
                        new
                        {
                            Id = "nr",
                            DisplayName = "South Ndebele"
                        },
                        new
                        {
                            Id = "oc",
                            DisplayName = "Occitan"
                        },
                        new
                        {
                            Id = "oj",
                            DisplayName = "Ojibwe"
                        },
                        new
                        {
                            Id = "cu",
                            DisplayName = "Old Church"
                        },
                        new
                        {
                            Id = "om",
                            DisplayName = "Oromo"
                        },
                        new
                        {
                            Id = "or",
                            DisplayName = "Oriya"
                        },
                        new
                        {
                            Id = "os",
                            DisplayName = "Ossetian"
                        },
                        new
                        {
                            Id = "pa",
                            DisplayName = "Panjabi"
                        },
                        new
                        {
                            Id = "pi",
                            DisplayName = "Pāli"
                        },
                        new
                        {
                            Id = "fa",
                            DisplayName = "Persian"
                        },
                        new
                        {
                            Id = "pl",
                            DisplayName = "Polish"
                        },
                        new
                        {
                            Id = "ps",
                            DisplayName = "Pashto"
                        },
                        new
                        {
                            Id = "pt",
                            DisplayName = "Portuguese"
                        },
                        new
                        {
                            Id = "qu",
                            DisplayName = "Quechua"
                        },
                        new
                        {
                            Id = "rm",
                            DisplayName = "Romansh"
                        },
                        new
                        {
                            Id = "rn",
                            DisplayName = "Kirundi"
                        },
                        new
                        {
                            Id = "ro",
                            DisplayName = "Romanian"
                        },
                        new
                        {
                            Id = "ru",
                            DisplayName = "Russian"
                        },
                        new
                        {
                            Id = "sa",
                            DisplayName = "Sanskrit (Saṁskṛta)"
                        },
                        new
                        {
                            Id = "sd",
                            DisplayName = "Sindhi"
                        },
                        new
                        {
                            Id = "se",
                            DisplayName = "Northern Sami"
                        },
                        new
                        {
                            Id = "sm",
                            DisplayName = "Samoan"
                        },
                        new
                        {
                            Id = "sg",
                            DisplayName = "Sango"
                        },
                        new
                        {
                            Id = "sr",
                            DisplayName = "Serbian"
                        },
                        new
                        {
                            Id = "gd",
                            DisplayName = "Scottish Gaelic"
                        },
                        new
                        {
                            Id = "sn",
                            DisplayName = "Shona"
                        },
                        new
                        {
                            Id = "si",
                            DisplayName = "Sinhala"
                        },
                        new
                        {
                            Id = "sk",
                            DisplayName = "Slovak"
                        },
                        new
                        {
                            Id = "sl",
                            DisplayName = "Slovene"
                        },
                        new
                        {
                            Id = "so",
                            DisplayName = "Somali"
                        },
                        new
                        {
                            Id = "st",
                            DisplayName = "Southern Sotho"
                        },
                        new
                        {
                            Id = "es",
                            DisplayName = "Spanish"
                        },
                        new
                        {
                            Id = "su",
                            DisplayName = "Sundanese"
                        },
                        new
                        {
                            Id = "sw",
                            DisplayName = "Swahili"
                        },
                        new
                        {
                            Id = "ss",
                            DisplayName = "Swati"
                        },
                        new
                        {
                            Id = "sv",
                            DisplayName = "Swedish"
                        },
                        new
                        {
                            Id = "ta",
                            DisplayName = "Tamil"
                        },
                        new
                        {
                            Id = "te",
                            DisplayName = "Telugu"
                        },
                        new
                        {
                            Id = "tg",
                            DisplayName = "Tajik"
                        },
                        new
                        {
                            Id = "th",
                            DisplayName = "Thai"
                        },
                        new
                        {
                            Id = "ti",
                            DisplayName = "Tigrinya"
                        },
                        new
                        {
                            Id = "bo",
                            DisplayName = "Tibetan Standard"
                        },
                        new
                        {
                            Id = "tk",
                            DisplayName = "Turkmen"
                        },
                        new
                        {
                            Id = "tl",
                            DisplayName = "Tagalog"
                        },
                        new
                        {
                            Id = "tn",
                            DisplayName = "Tswana"
                        },
                        new
                        {
                            Id = "to",
                            DisplayName = "Tonga (Tonga)"
                        },
                        new
                        {
                            Id = "tr",
                            DisplayName = "Turkish"
                        },
                        new
                        {
                            Id = "ts",
                            DisplayName = "Tsonga"
                        },
                        new
                        {
                            Id = "tt",
                            DisplayName = "Tatar"
                        },
                        new
                        {
                            Id = "tw",
                            DisplayName = "Twi"
                        },
                        new
                        {
                            Id = "ty",
                            DisplayName = "Tahitian"
                        },
                        new
                        {
                            Id = "ug",
                            DisplayName = "Uighur"
                        },
                        new
                        {
                            Id = "uk",
                            DisplayName = "Ukrainian"
                        },
                        new
                        {
                            Id = "ur",
                            DisplayName = "Urdu"
                        },
                        new
                        {
                            Id = "uz",
                            DisplayName = "Uzbek"
                        },
                        new
                        {
                            Id = "ve",
                            DisplayName = "Venda"
                        },
                        new
                        {
                            Id = "vi",
                            DisplayName = "Vietnamese"
                        },
                        new
                        {
                            Id = "vo",
                            DisplayName = "Volapük"
                        },
                        new
                        {
                            Id = "wa",
                            DisplayName = "Walloon"
                        },
                        new
                        {
                            Id = "cy",
                            DisplayName = "Welsh"
                        },
                        new
                        {
                            Id = "wo",
                            DisplayName = "Wolof"
                        },
                        new
                        {
                            Id = "fy",
                            DisplayName = "Western Frisian"
                        },
                        new
                        {
                            Id = "xh",
                            DisplayName = "Xhosa"
                        },
                        new
                        {
                            Id = "yi",
                            DisplayName = "Yiddish"
                        },
                        new
                        {
                            Id = "yo",
                            DisplayName = "Yoruba"
                        },
                        new
                        {
                            Id = "za",
                            DisplayName = "Zhuang"
                        });
                });

            modelBuilder.Entity("Phrasebook.Data.Models.Phrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CorrectnessCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstLanguagePhrase")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ForeignLanguagePhrase")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ForeignLanguageSynonyms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LexicalItemType")
                        .HasColumnType("int");

                    b.Property<int>("PhrasebookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhrasebookId");

                    b.ToTable("Phrases");
                });

            modelBuilder.Entity("Phrasebook.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityProvider")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SignedUpOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Phrasebook.Data.Models.Book", b =>
                {
                    b.HasOne("Phrasebook.Data.Models.Language", "FirstLanguage")
                        .WithMany()
                        .HasForeignKey("FirstLanguageId");

                    b.HasOne("Phrasebook.Data.Models.Language", "ForeignLanguage")
                        .WithMany()
                        .HasForeignKey("ForeignLanguageId");

                    b.HasOne("Phrasebook.Data.Models.User", "User")
                        .WithMany("Phrasebooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstLanguage");

                    b.Navigation("ForeignLanguage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Phrasebook.Data.Models.Phrase", b =>
                {
                    b.HasOne("Phrasebook.Data.Models.Book", "Phrasebook")
                        .WithMany("Phrases")
                        .HasForeignKey("PhrasebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrasebook");
                });

            modelBuilder.Entity("Phrasebook.Data.Models.Book", b =>
                {
                    b.Navigation("Phrases");
                });

            modelBuilder.Entity("Phrasebook.Data.Models.User", b =>
                {
                    b.Navigation("Phrasebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
